### ISSUE TITLE
Web Application for audio-encryption

### ISSUE THREAD

**Issue by vijeth-aradhya** [vijeth-aradhya/audio-encryption#1]
This module requires a web application to start with, since anyone should be able to generate the audio-encrypted data.

- Either Django or Ruby on Rails is appreciated. 
- React.js or Bootstrap for frontend
- MySQL for backend

**Task** : Initialize the web application

**Comment by singh1114** [comment]
I have initialized a django app with all the requirements. Please accept the PR.
